### COPY THIS FILE to config_local.yml and fill with your details

DEVELOPER_KEY: # youtube developer key
BQ_KEY_FILE: # Change this to the path of your JSON key provided by Google
PROJECT_ID: # Bigquery project to save to
DATASET: # Bigquery dataset to save to
SAVE_TABLE_SEARCH: # Bigquery table to save to

# Mailgun config is used to send email updates. You can leave blank to disable.
mailgun:
  mailgun_default_smtp_login:
  mailgun_api_base_url:
  mailgun_api_key:
  email_to_notify:
